### ISSUE TITLE
Problem with string

### ISSUE THREAD

**Issue by Qwebeck** [Artinov/home-work-13-Qwebeck#1]
Hello
I have a problem with server calculation
Server makes ariphmetic with string
For this homework i do so operation:
I took string 'response.url' and with help of split get from this string arguments 'a' and 'b'
Than with Number() function transform tham in numbers 
In console all ariphmetic work
But server dont want do operation with numbers and works only with string
Can you help me and tell why this problem appear?
Thank you

**Comment by eko24ive** [comment]
Hi @Qwebeck is there any error messages in terminal ?
If so - please copy-paste them here

**Comment by Qwebeck** [comment]
_http_outgoing.js:555
    throw new TypeError('First argument must be a string or Buffer');
    ^

TypeError: First argument must be a string or Buffer
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:555:11)
    at Server.<anonymous> (D:\artinov\home-work-13-Qwebeck\index.js:19:13)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)

**Comment by eko24ive** [comment]
So, as you can see NodeJS tries to tell you that response's `.end()` method can work only with sting or Buffer. Below you can see stack trace, where you can find your file among other NodeJS code:
`at Server. (D:\artinov\home-work-13-Qwebeck\index.js:19:13)`
This line says that error is at 19th line on 13th cursor position in index.js file - this is exactly where you call `response.end(a+b)`, so what you have to do is convert result of `a+b` operations, which is number, to string, so `.end()` method can send it to client.

**Comment by Qwebeck** [comment]
Thank you
